In [1]:
import numpy as np

## 1. Array creation

There are several ways to create a numpy array

### 1.1. From a single sequence

Passing a single sequence to the `np.array` will generate a `ndarray` object. Pretty much any sequence will do. The type of the numpy array will be deduced from the type of the elements in the sequence, although it can be explicitly stated.

In [2]:
# from a list
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# from tuple, with dtype
np.array((4, 5, 6), dtype=np.float32)

array([4., 5., 6.], dtype=float32)

Notice that we can provide nested sequences and NumPy will generate multidimensional arrays: sequences of sequences will be transformed into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [4]:
# from nested list
np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

array([[1, 2, 3],
       [4, 5, 6]])

### 1.2. Built-in constructors

NumPy provides multiple functions to generate arrays from a given shape. This is often useful when we do not know the content of the array but we know its shape

In [5]:
shape = (2, 3)

In [6]:
np.ones(shape=shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros(shape=shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.empty(shape=shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

We can also use an already created array to generate other arrays

In [9]:
arr = np.array([[1, 2], [3, 4]])
np.ones_like(arr)

array([[1, 1],
       [1, 1]])

In [10]:
np.zeros_like(arr)

array([[0, 0],
       [0, 0]])

In [11]:
np.empty_like(arr)

array([[27559037,        0],
       [29439968, 30589136]])

### 1.3. Built-in sequence generators

It is also possible to create sequences of numbers using NumPy. `arange` is analogous to Python's `range`

In [12]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

It also accepts floating point values

In [13]:
np.arange(start=0.5, stop=2.5, step=0.3)

array([0.5, 0.8, 1.1, 1.4, 1.7, 2. , 2.3])

In [14]:
np.arange(start=0.5, stop=2.5, step=0.3)[3]

1.4000000000000001

`linspace` can mitigate by dividing the interval evenly without relying on cumulative step-based additions.

In [15]:
np.linspace(start=0.5, stop=2.5, num=7)

array([0.5       , 0.83333333, 1.16666667, 1.5       , 1.83333333,
       2.16666667, 2.5       ])

## 2. Array Properties

Below you will find some of the most important properties of an array object:

In [16]:
type(np.arange(6))

numpy.ndarray

### 2.1. Number of dimensions

The number of axes (dimensions) of the array.

In [17]:
np.arange(6).ndim

1

In [18]:
np.zeros((3,2)).ndim

2

In [19]:
np.zeros((3, 2, 2)).ndim

3

### 2.2. Array shape

The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with `n` rows and `m` columns, shape will be `(n, m)`. The length of the shape tuple is therefore the number of axes, `ndim`.

In [20]:
n, m = 2, 3
np.zeros((n, m)).shape

(2, 3)

### 2.3. Size

The total number of elements of the array.

In [21]:
n, m = 2, 3
np.zeros((n, m)).size

6

This is equal to the product of the elements of shape.

In [22]:
n * m

6

### 2.4. Data type

An object describing the type of the elements in the array.

In [23]:
np.arange(5).dtype

dtype('int64')

One can create or specify `dtype`’s using standard Python types. Additionally NumPy provides types of its own. `numpy.int32`, `numpy.int16`, and `numpy.float64` are some examples.

In [24]:
np.array([1, 2], dtype=np.int32)

array([1, 2], dtype=int32)

In [25]:
np.array([1, 2], dtype=float)

array([1., 2.])

When assigning elements, we need to take into account the type of the element to assing as well as the array we are trying to modify

In [27]:
x = np.array([1, 2], dtype=np.int32)
x.dtype

dtype('int32')

In [28]:
x[0] = 9.4567676

In [29]:
x

array([9, 2], dtype=int32)

We can coerce the dtype of an existing array using `astype`

In [30]:
x = x.astype(float)

In [31]:
x[0] = 9.4567676
x

array([9.4567676, 2.       ])

----