In [2]:
import numpy as np

Create arrays

In [3]:
array_1d = np.arange(10)
array_2d = np.arange(20).reshape(5, 4)

In [4]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 1. Indexing

You can index NumPy arrays in the same ways you can slice Python lists.

In [7]:
array_1d[0]

0

Negative indexes work the same in NumPy arrays

In [9]:
array_1d[-1]

9

In [10]:
array_1d.tolist()[-1]

9

For 2d arrays you have to take into account that you have to use a different index for each axis. Lets select the element 0 from the first axis and the element 2 from the second axis.

In [13]:
i, j = 0, 2

We can pass a tuple of indices such that

In [14]:
array_2d[i, j]

2

or we can use a pair of brackets for each axis

In [16]:
array_2d[i][j]

2

If we only use a single index for a 2-dimensional array we will get the first row

In [22]:
array_2d[i]

array([0, 1, 2, 3])

## 2. Slicing

As with indexing, you can slice NumPy arrays in the same ways you can slice Python lists.

In [19]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array_1d[:3]

array([0, 1, 2])

In [18]:
array_1d[2:4]

array([2, 3])

In [20]:
array_1d[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
array_1d[-2:]

array([8, 9])

For n-dimensional arrays we need to take into account the different axis

In [24]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

The `:` indicates NumPy that it needs to select all the elements in the axis. The `1:3` indicates NumPy that it needs to retrieve columns 1 and 2 (remember the end slice is not inclusive in Python).

In [25]:
array_2d[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

We can also pass an iterable with the columns and rows we want to select

In [30]:
array_2d[:, [1, 2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [31]:
array_2d[[0, 4], [1, 2]]

array([ 1, 18])

In [27]:
# only columns 1 and 2 from the first row
array_2d[0, 1:3]

array([1, 2])

## 3. Iteration

Iteration also works as in Python

In [32]:
for element in array_1d:
    print(element)

0
1
2
3
4
5
6
7
8
9


Iterating over multidimensional arrays is done with respect to the first axis:

In [33]:
for row in array_2d:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


To iterate over the columns too we need to add another loop

In [35]:
for row in array_2d:
    for element in row:
        print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


or we can use the function `.flatten()` to transform our multidimensional array into a 1d array

In [36]:
for element in array_2d.flatten():
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Nesting loops for n-dimensional arrays can generate messy code

In [64]:
array_4d = np.arange(16).reshape(2, 2, 2, 2)

In [67]:
for x in array_4d:
    for y in x:
        for z in y:
            for element in z:
                print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


NumPy provides `nditer` to deal with the iteration problem.

### 3.1. nditer

The iterator object `nditer`, introduced in NumPy 1.6, provides many flexible ways to visit all the elements of one or more arrays in a systematic fashion.

In [37]:
np.nditer?

Init signature: np.nditer(self, /, *args, **kwargs)
Docstring:     
nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``co

Basic example: iterate over all elements of the array

In [47]:
for element in np.nditer(array_2d, order='C'):  # by default, order is 'C' (C language), row-major
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


With `nditer` we can change the [iteration order of the array](https://en.wikipedia.org/wiki/Row-_and_column-major_order).

In [48]:
for element in np.nditer(array_2d, order='F'):  # we can change order to 'F' (Fortran language), column-major
    print(element)

0
4
8
12
16
1
5
9
13
17
2
6
10
14
18
3
7
11
15
19


`F` order is equivalent to iterating over the transposed array with `C` ordering.

In [51]:
for element in np.nditer(array_2d.T, order='C'):
    print(element)

0
4
8
12
16
1
5
9
13
17
2
6
10
14
18
3
7
11
15
19


By default, order is `C`, and that is why the flag `external_loop` is able to get the whole array as a single chunk

In [57]:
for x in np.nditer(array_2d, flags=['external_loop'], order='C'):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


If we try to iterate with order `F` we will get a chunk for each column

In [60]:
for x in np.nditer(array_2d, flags=['external_loop'], order='F'):
    print(x)

[ 0  4  8 12 16]
[ 1  5  9 13 17]
[ 2  6 10 14 18]
[ 3  7 11 15 19]


Test this behaviour with an array of order F, we expect a single chunk when iterating with order `F`.

In [59]:
array_2d_order_F = np.array(array_2d, order='F')
for x in np.nditer(array_2d_order_F, flags=['external_loop'], order='F'):
    print(x)

[ 0  4  8 12 16  1  5  9 13 17  2  6 10 14 18  3  7 11 15 19]


In [61]:
for x in np.nditer(array_2d_order_F, flags=['external_loop'], order='C'):
    print(x)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


However, we can add a flag to buffer the elements such that the interpreter is able to see bigger chunks:

In [101]:
for x in np.nditer(array_2d_order_F, flags=['buffered', 'external_loop'], order='C'):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Lastly, we can iterate over a sequence of arrays, as long as their shape is compatible

In [104]:
for x, y in np.nditer([array_2d, np.arange(5).reshape(-1,1)]):
    print(x, y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2
12 3
13 3
14 3
15 3
16 4
17 4
18 4
19 4


Notice how the array with less dimensions is broadcast to match the shape. With incompatible shapes this would not work

In [105]:
for x, y in np.nditer([array_2d, np.arange(4).reshape(-1,1)]):
    print(x, y)

ValueError: operands could not be broadcast together with shapes (5,4) (4,1) 

Many more features explained in [the documentation](https://numpy.org/doc/2.1/reference/arrays.nditer.html).

## 4. Modifying elements

Operations that select a part of the array can be used to set elements too:

In [84]:
array = np.arange(9).reshape(3,3)

Modify element in row `0` and column `j`

In [90]:
i, j = 0, 0

array[i, j] = 31
array

array([[   31, -2000,   200],
       [  300, -2000,   500],
       [  900,   900,   900]])

We can set a particular slice of the array

In [91]:
array[:, 1] = -20
array

array([[ 31, -20, 200],
       [300, -20, 500],
       [900, -20, 900]])

But the value needs to be broadcastable or it needs to be a sequence of the same shape than the sliced sequence

In [92]:
array[-1] = np.array([0, 1])

ValueError: could not broadcast input array from shape (2,) into shape (3,)

The exception dissapears when we set a matching shape

In [96]:
array[-1] = np.array([0, 1, -1])
array

array([[ 3100, -2000, 20000],
       [30000, -2000, 50000],
       [    0,     1,    -1]])

In [93]:
array[-1] = [9] * 3
array

array([[ 31, -20, 200],
       [300, -20, 500],
       [  9,   9,   9]])

`nditer` can also be used by setting `readwrite` as an argument of `op_flag`

In [94]:
for element in np.nditer(array, op_flags=['readwrite']):
    element[...] = element * 100

array

array([[ 3100, -2000, 20000],
       [30000, -2000, 50000],
       [  900,   900,   900]])

----