In [2]:
import numpy as np

## 1. Reshape

Reshape allows us the set a new shape to an array. It does not change the elements of the array but the way they are disposed.

In [23]:
array = np.arange(8)
array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
array.shape

(8,)

But we want to change it to (4, 2). We can call on any array the method `reshape`

In [24]:
array.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

It is also possible to call the function `reshape` from the library and pass an array

In [25]:
np.reshape(array, (4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

The new shape must be compatible with the the old one.

In [12]:
array.reshape(10, 1)

ValueError: cannot reshape array of size 8 into shape (10,1)

In [13]:
array.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
array.reshape((2, 2, 2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

We can even add an extra dimension

In [30]:
array.reshape((2, 4, 1))

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

## 2. Transpose

Transposing an array means to swaps its axis. We can't set a particular shape, just swap the axis' of an array.

In [18]:
array = np.arange(6).reshape(2, 3)

In [19]:
array

array([[0, 1, 2],
       [3, 4, 5]])

For a 2-dimension array we can transpose its axis 0 and 1:

In [20]:
np.transpose(array, axes=(1, 0))

array([[0, 3],
       [1, 4],
       [2, 5]])

The new array has the the old's array axis 1 as axis 0, and the old's array axis 0 as axis 1. There is also a convenient attribute, `T`, that also allows to transpose the array.

In [21]:
array.T

array([[0, 3],
       [1, 4],
       [2, 5]])

-----