In [1]:
import numpy as np

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

## 1. Basic array operations

### 1.1. Arithmetic operations

In [2]:
A = np.arange(5)
B = np.ones_like(A) * 3

In [3]:
A + B

array([3, 4, 5, 6, 7])

In [4]:
A - B

array([-3, -2, -1,  0,  1])

In [5]:
A * B

array([ 0,  3,  6,  9, 12])

In [6]:
A / B

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

### 1.2. Orderting operations

In [7]:
A = np.arange(10)
np.random.shuffle(A)
A

array([9, 6, 5, 3, 0, 7, 8, 4, 1, 2])

`argsort` retrieves the sorted indices

In [8]:
sorted_indices = np.argsort(A)
A[sorted_indices]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`argmax` and `argmin` retrieve the indices where the max and min values can be found in the array

In [9]:
max_val_idx = np.argmax(A)
print(f"Max value: {A[max_val_idx]} can be found on index {max_val_idx}")

Max value: 9 can be found on index 0


In [10]:
min_val_idx = np.argmin(A)
print(f"Min value: {A[min_val_idx]} can be found on index {min_val_idx}")

Min value: 0 can be found on index 4


### 1.3. Reduction operations

In [11]:
A = np.arange(15).reshape(3, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Sum all elements of the array

In [12]:
A.sum()

105

We can select the axis in which to perform the aggregation

In [13]:
A.sum(axis=0)

array([15, 18, 21, 24, 27])

In [14]:
A.sum(axis=1)

array([10, 35, 60])

Other reduction functions behave the same

In [15]:
A.mean()

7.0

In [16]:
A.mean(axis=0)

array([5., 6., 7., 8., 9.])

In [17]:
A.mean(axis=1)

array([ 2.,  7., 12.])

### 1.4. Set operations

In [36]:
A = np.arange(start=0, stop=10)
B = np.arange(start=5, stop=15)
print(f"Array A: {A}  |  Array B: {B}")

Array A: [0 1 2 3 4 5 6 7 8 9]  |  Array B: [ 5  6  7  8  9 10 11 12 13 14]


Set intersection operations

In [22]:
np.intersect1d(A, B)

array([5, 6, 7, 8, 9])

Set union operations

In [23]:
np.union1d(A, B)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Set difference operations

In [25]:
np.setdiff1d(A, B)

array([0, 1, 2, 3, 4])

In [37]:
np.setdiff1d(B, A)

array([10, 11, 12, 13, 14])

Get unique values of an array

In [28]:
ones = np.ones(5)
ones[-1] = 20

np.unique(ones)

array([ 1., 20.])

In [30]:
unique_vals, count = np.unique(ones, return_counts=True)
unique_vals

array([ 1., 20.])

In [31]:
count

array([4, 1])

### 1.5. Join operations

In [35]:
A = np.arange(start=0, stop=10)
B = np.arange(start=5, stop=15)
print(f"Array A: {A}  |  Array B: {B}")

Array A: [0 1 2 3 4 5 6 7 8 9]  |  Array B: [ 5  6  7  8  9 10 11 12 13 14]


Stacks along an `existing axis`

In [41]:
np.concatenate([A, B])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In fact, specifying `axis=1` for 1D case will not work because there is no axis 1

In [52]:
np.concatenate([A, B], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

Stack horizontally (column-wise)

In [45]:
np.hstack([A, B])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

Stacks vertically (row-wise)

In [46]:
np.vstack([A, B])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

Stacks along a `new axis`

In [51]:
np.stack([A, B], axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [48]:
np.stack([A, B], axis=1)

array([[ 0,  5],
       [ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14]])

## 2. Broadcasting rules

A process that works automagically (no need to implement anything) and defines how operations are applied on arrays with different shapes. When 2 arrays have different but compatible shapes NumPy will create an implicit array using the array with less dimensions to match the array with more dimensions

In [37]:
X = np.arange(5)

In [39]:
X + 20

array([20, 21, 22, 23, 24])

Shapes must be compatible. NumPy cannot broadcast an array with shape (2,) into an array with shape (5, )

In [40]:
X + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

Broadcasting will work with higher dimensions too:

In [46]:
X = np.arange(20).reshape(4, 5)
Y = np.arange(5)

In [47]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 2.1. Broadcasting rules

A more formal definition of broadcasting rules:

1. If array shapes differ, left-pad de smaller `shape` with 1s.
2. If any dimension does not match, broadcast the dimension with size=1.
3. If neither non-matching dimension is 1, raise an error.

## 3. Universal functions (ufuncs)

A universal function (or `ufunc` for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features.

In the documentation you can find a [list of ufuncs](https://numpy.org/doc/2.1/reference/ufuncs.html).

Binary universal functions:

In [155]:
A = np.zeros((3, 3))
B = np.random.normal(0, 1, size=(3, ))

In [158]:
B

array([ 0.60884383, -1.04525337,  1.21114529])

In [159]:
A + B

array([[ 0.60884383, -1.04525337,  1.21114529],
       [ 0.60884383, -1.04525337,  1.21114529],
       [ 0.60884383, -1.04525337,  1.21114529]])

Unary universal functions

In [165]:
np.log(np.ones((3, 3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

You can define you own `ufunc`s using `frompyfunc`

In [174]:
def _custom_divide(a, b):
  return a / b

custom_divide = np.frompyfunc(_custom_divide, nin=2, nout=1)
custom_divide(B * 5, B)

array([5.0, 5.0, 5.0], dtype=object)

Why doing this? This implements automagically broadcasting to your function

## 4. Linear algebra

### 4.1. Matrix multiplication

In [142]:
A = np.random.normal(size=(4, 5))
B = np.random.normal(size=(5, 10))

In [144]:
np.matmul(A, B).shape

(4, 10)

The matmul function implements the semantics of the `@` operator

In [145]:
(A @ B).shape

(4, 10)

If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

In [146]:
A = np.ones([9, 5, 7, 4])
B = np.ones([9, 5, 4, 3])

In [147]:
np.matmul(A, B).shape

(9, 5, 7, 3)

### 4.2. Hadamar product

In [139]:
A = np.arange(9.0).reshape((3, 3))
B = np.arange(3.0)

In [141]:
A * B

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [140]:
np.multiply(A, B)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

### 4.3. Determinants

In [135]:
A = np.array([[1, 2], [3, 4]])

In [136]:
np.linalg.det(A)

-2.0000000000000004

### 4.3. Inverse of a matrix

In [116]:
A = np.array([[1, 2], [3, 5]])

In [119]:
inverse_A = np.linalg.inv(A)
inverse_A

array([[-5.,  2.],
       [ 3., -1.]])

In [121]:
np.round(
    A @ inverse_A, 0
)

array([[1., 0.],
       [0., 1.]])

For non-square matrices we can compute the pseudo-inverse

In [132]:
B = np.array([[1, 2, 7], [3, 5, 1]])
B

array([[1, 2, 7],
       [3, 5, 1]])

In [133]:
inverse_B = np.linalg.pinv(B)

In [134]:
np.round(
    B @ inverse_B, 0
)

array([[ 1., -0.],
       [ 0.,  1.]])

### 4.4. Linear systems of equations

Solves `A x = B`

In [106]:
A = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

In [107]:
x = np.linalg.solve(A, b)
x

array([-1.,  1.])

In [110]:
np.testing.assert_allclose(A @ x, b)

Notice that we can compute the inverse of a function using `solve` and the inverse properties, by which `A A' = I`

In [114]:
np.linalg.inv(A)

array([[-5.,  2.],
       [ 3., -1.]])

In [115]:
np.linalg.solve(A, np.identity(len(A)))

array([[-5.,  2.],
       [ 3., -1.]])

### 4.5. Eigen decomposition

Eigen values for a squared matrix can be obtained using `eig`

In [67]:
A = np.diag((1, 2, 3))
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [68]:
eigenvalues, eigenvectors  = np.linalg.eig(A)

In [81]:
eigenvalues

array([1., 2., 3.])

In [82]:
eigenvectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

If the matrix is not squared we need to use SVD

In [88]:
B = np.random.normal(size=(3, 4))
U, S, Vh = np.linalg.svd(B, full_matrices=True)

### 4.6. Least Squares

In [60]:
def generate_lin_reg(size=100, seed=0, beta=0.4, intercept=None):
    np.random.seed(seed)
    X = np.random.normal(0, 1, size=(size, 1))
    y = beta * X + np.random.normal(0, 0.2, (size, 1))
    if intercept is not None:
        y += intercept

    return X, y

In [56]:
X, y = generate_lin_reg(size=100, seed=0, beta=0.4)
beta_hat, resids, rank, svals = np.linalg.lstsq(X, y)
print(beta_hat.item())

0.4238215271891797


If we manually compute the beta parameter using the formula of Ordinary Least Squares we get

In [59]:
def ols(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

ols(X, y)

array([[0.42382153]])

What if we want to estimate an intercept?

In [61]:
X, y = generate_lin_reg(size=100, seed=0, beta=0.4, intercept=3)

We add a column of ones to the `X` matrix

In [62]:
ones_col = ones_col = np.ones((len(X), 1))
_X = np.hstack((ones_col, X))

In [64]:
beta_hat, resids, rank, svals = np.linalg.lstsq(_X, y)
print(beta_hat)

[[3.01503062]
 [0.42293969]]


----