In [1]:
import numpy as np

## 1. Views
A view of a NumPy array is a new array object that shares the same data as the original array. Modifications to the view affect the original array and vice versa. Views are created when you `slice` or `reshape` an array. They provide a window into the original data without duplicating it.

In [2]:
A = np.arange(5)
view_A = A[2:4]
view_A

array([2, 3])

If we modify the view of the array `we also modify the original array`

In [3]:
view_A[0] = -20
view_A

array([-20,   3])

In [4]:
A

array([  0,   1, -20,   3,   4])

## 2. Copies

A copy of a NumPy array is a new array object with its own data. Changes to the copy do not affect the original array. A copy is explicitly created when you call the `.copy()` method on an array. This data duplication ensures independence between the original and the new array.

In [5]:
B = np.arange(5)
copy_B = A[2:4].copy()
copy_B

array([-20,   3])

In [6]:
copy_B[0] = -20
copy_B

array([-20,   3])

In [7]:
A

array([  0,   1, -20,   3,   4])

## 3. View vs copy

| **Operation**                | **Is view or copy?**                  |
|------------------------------|---------------------------------------|
| Array slicing                | View                                  |
| Array reshaping              | View (not always possible, else copy) |
| `.copy()`                    | Copy                                  |
| Basic arithmetic (array + 2) | Copy                                  |

You can use `may_share_memory` to help identifying whether two arrays are independent (copy) or not (view)

In [8]:
np.may_share_memory(A, view_A)

True

In [10]:
np.may_share_memory(B, copy_B)

False

----