In [1]:
import numpy as np

## 1. Generating random numbers

The `numpy.random` module provides functions to generate random numbers in various forms.

Uniformly Distributed:

In [2]:
np.random.random()

0.5347324509067745

Uniformly distributed integers

In [3]:
np.random.randint(low=1, high=20, size=1)

array([12])

## 2. Sampling from sequences

We can use the `numpy.random` module to randomly select elements from arrays or other sequences.

### 2.1. Single random choice

In [4]:
array = np.arange(100)
choice = np.random.choice(array)
choice

80

### 2.2. Random sample

With replacement

In [5]:
array = np.arange(10)
sample = np.random.choice(array, size=5, replace=True)
sample

array([9, 5, 2, 0, 2])

Without replacement

In [6]:
array = np.arange(10)
sample = np.random.choice(array, size=5, replace=False)
sample

array([2, 0, 5, 3, 9])

## 3. Distributions

NumPy provides access to various probability distributions, useful for simulations and statistical modeling.

In [7]:
dist_names = ['normal', 'gamma', 'exponential', 'f', 'chisquare', 'beta']

In [8]:
for dist in dist_names:
    print(getattr(np.random, dist))

<built-in method normal of numpy.random.mtrand.RandomState object at 0x70eeac30de40>
<built-in method gamma of numpy.random.mtrand.RandomState object at 0x70eeac30de40>
<built-in method exponential of numpy.random.mtrand.RandomState object at 0x70eeac30de40>
<built-in method f of numpy.random.mtrand.RandomState object at 0x70eeac30de40>
<built-in method chisquare of numpy.random.mtrand.RandomState object at 0x70eeac30de40>
<built-in method beta of numpy.random.mtrand.RandomState object at 0x70eeac30de40>


Each distribution has its own documentation:

In [9]:
print(getattr(np.random, dist).__doc__)


        beta(a, b, size=None)

        Draw samples from a Beta distribution.

        The Beta distribution is a special case of the Dirichlet distribution,
        and is related to the Gamma distribution.  It has the probability
        distribution function

        .. math:: f(x; a,b) = \frac{1}{B(\alpha, \beta)} x^{\alpha - 1}
                                                         (1 - x)^{\beta - 1},

        where the normalization, B, is the beta function,

        .. math:: B(\alpha, \beta) = \int_0^1 t^{\alpha - 1}
                                     (1 - t)^{\beta - 1} dt.

        It is often seen in Bayesian inference and order statistics.

        .. note::
            New code should use the `~numpy.random.Generator.beta`
            method of a `~numpy.random.Generator` instance instead;
            please see the :ref:`random-quick-start`.


        Parameters
        ----------
        a : float or array_like of floats
            Alpha, positive (>0).
        b 

In [10]:
np.random.normal(loc=0, scale=1, size=10)

array([ 0.62409538,  0.32338563, -0.56415303,  0.89673269,  0.42227095,
        1.23333401, -0.62334558, -0.38694414,  0.06180902,  0.36871428])

In [11]:
np.random.uniform(low=-10, high=10, size=10)

array([ 3.34143107, -2.00682416, -7.88051768, -6.84625539, -3.95949979,
        9.39141989,  7.81959999,  2.63138956,  5.42466541, -9.02911687])

## 4. Shuffling and Permutations

You can shuffle data or generate random permutations using the `shuffle` and `permutation` methods.

### 4.1. Shuffle (In-place)

In [12]:
array = np.array([1, 2, 3, 4, 5])

np.random.shuffle(array)
array

array([3, 5, 4, 1, 2])

### 4.2. Permutation (Creates a New Array)

In [13]:
array = np.array([1, 2, 3, 4, 5])

perm = np.random.permutation(array)
perm

array([5, 3, 1, 2, 4])

In [14]:
array

array([1, 2, 3, 4, 5])

## 5. Random seeds

To produce reproducible results, you can seed the random number generator using `np.random.seed`.

In [15]:
for _ in range(3):
    arr = np.random.normal(loc=0, scale=1, size=5)
    print(arr)

[ 0.37699854  1.70597055  1.51574901 -0.83910552 -0.60505282]
[-0.62199808 -0.04983061 -0.38302372  0.18882397  0.03276747]
[-0.35109276 -0.90136367  1.85753395 -0.00726418 -0.58436322]


The [new standard](https://numpy.org/neps/nep-0019-rng-policy.html) is to instantiate a generator object with a seed and pass it around

In [20]:
for _ in range(3):
    rng = np.random.default_rng(2021)
    arr = rng.normal(loc=0, scale=1, size=5)
    print(arr)

[-0.0688612  -0.68696559 -0.7884868   1.07600685 -0.01052417]
[-0.0688612  -0.68696559 -0.7884868   1.07600685 -0.01052417]
[-0.0688612  -0.68696559 -0.7884868   1.07600685 -0.01052417]


But be careful, a single instance will generate different random numbers (this is expected and intended). This ensures high-quality randomness for stochastic processes.

In [21]:
rng = np.random.default_rng(2021)

for _ in range(3):
    arr = rng.normal(loc=0, scale=1, size=5)
    print(arr)

[-0.0688612  -0.68696559 -0.7884868   1.07600685 -0.01052417]
[-0.45565263 -0.03866147 -2.62149639 -0.82323987 -1.54276562]
[ 0.45451241 -0.39209841  0.95682255  0.38092829 -1.22445644]


If your goal is to use the same generator across iterations and produce identical outputs, resetting the seed is necessary.

## 6. Examples
### 6.1. Coin toss

In [27]:
# Simulate 10 coin tosses (0=Heads, 1=Tails)
coin_toss = np.random.choice([0, 1], size=10)
coin_toss

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1])

### 6.2. Estimating PI

In [25]:
def estimate_pi(n_points):
    x = np.random.uniform(-1, 1, size=n_points)
    y = np.random.uniform(-1, 1, size=n_points)

    # Points inside the unit circle
    inside_circle = (x**2 + y**2) <= 1
    pi_estimate = (inside_circle.sum() / n_points) * 4
    return pi_estimate

In [26]:
for n in [10, 10_000, 100_000]:
    print(estimate_pi(n_points=n))

3.2
3.1224
3.15056


---